### ISSUE TITLE
Danks from Dankstorage can pickup hook entity(item?)

### ISSUE THREAD

**Issue by WhitePhant0m** [CammiePone/Hookshot#24]
Danks from Dankstorage can pickup the hook entity which is shot out from the hookshot if the dank is set on ANY pickup mode, and if it gets picked up, the player will float until another hook is fired.

My guess is that the entity is an item which would be why danks can pick it up.

mc ver: 1.18.1
hookshot ver: r24
dankstorage ver: 3.5
other mods: REI and it's dependencies

**Comment by CammiePone** [comment]
It's a projectile, not an item. Blame dankstorage for being written in a way that it picks up projectiles. Or just not checking if the projectile doesn't have an item attached, because lo and behold, projectiles are forced to. Putting null in here would just crash the game if the player were to somehow attempt to pick it up (one instance would be if you're a Phantom from Origins phased in a block and fire the Hookshot).
![image](https://user-images.githubusercontent.com/16853086/152647809-10cfd7c0-08e7-4daa-8657-1f561ae5d871.png)
